### ISSUE TITLE
argument for session

### ISSUE THREAD

**Issue by paola-o** [BIDS-Apps/HCPPipelines#20]
Is there any way to specify a session name (versus running through all existing sessions for every subject) in the --participant_label argument?

Thanks,
Paola

**Comment by DavidEWarrenPhD** [comment]
I agree that adding session would be very handy — not least because the current subject/session handling is not great.  For sub-001/ses-1:
```
sub-001/MNINonLinear/Results/        
├── ses-1_task-rest_run-1_bold
├── ses-1_task-rest_run-2_bold
├── ses-1_task-rest_run-3_bold
└── ses-1_task-rest_run-4_bold
```
That said, is this going to be challenging because of how the HCP Pipeline scripts handle pathing of datasets below the T?w and MNINonLinear directories?  Would it be necessary to collapse the typical BIDS `sub-?/ses-?` directory structures to `sub-?_ses-?`?

**Comment by rhancockn** [comment]
Support for specifying a session was added in #52.
